### PR TITLE
Add FOR components to node, fix RealChute compatibility

### PR DESCRIPTION
**Pull request by StupidChris**
I've got a few complaints about the Mk16 chute breaking under certain conditions with RealChute installed. After investigation, turns out this isue was caused from Stock Revamp messing up my MM patches.

While I was at it making sure your patches didn't mess up RealChute anymore, I also added FOR components to all your patches (at least I think all) so that people can access BEFORE/AFTER nodes correctly for this, and fixed the RealChute patch on your own created parts.

Haven't been tested, but this should work.

### CODE REVIEW

**Comment by NathanKell** [comment]
@StupidChris  please don't add the FOR, actually. FOR[VenStockRevamp] runs very, very late, whereas most all these patches should run *before* other patches. Not on First, because it'd be good if people could run before these if necessary, but the Legacy pass is actually IMO a *great* pass to run them on.

**Comment by NathanKell** [comment]
Whoops, totally missed this at the time, didn't realize it was 3 days old. Oops.
@VenVen please see argument above. : ]

**Comment by VenVen** [comment]
How do you do this legacy pass?

**Comment by NathanKell** [comment]
@VenVen  it's the pass that things without a pass run on.
i.e. @PART[liquidEngine] <<< runs on the :LEGACY pass
@PART[liquidEngine]:FIRST or :FOR[something] or whatever <<< runs on that pass, not the LEGACY pass.

**Comment by NathanKell** [comment]
To clarify: Since Stock Revamp has no plugins, by definition FOR[VenStockRevamp] will run later than any plugin-containing mod's pass. For example, any mod that includes a plugin that changes a Squad part and does not run a *second* patch on :AFTER[VenStockRevamp] will have its changes overwritten if this mod runs on :FOR[VenStockRevamp].

**Comment by VenVen** [comment]
Oh, ok. Thanks for clearing that up.

**Comment by NathanKell** [comment]
@VenVen  since @StupidChris  did stuff in different commits, we can just revert the FOR commit and all should be well I think. But let's wait on hearing back from @StupidChris as he'd know best (like, if there was a bit of that in other commits, or something extra in that commit).

**Comment by StupidChris** [comment]
Nope, I did this in separate commits for this specific reason. I added the FOR while attempting to fix the RealChute problem with an AFTER pass on my side, but realized I couldn't, and that it would be silly anyway. So yeah you can just revert th first one.

**Comment by NathanKell** [comment]
@StupidChris cool! :)

@VenVen, with your permission shall I do the revert then?

**Comment by VenVen** [comment]
@NathanKell have at it.

**Comment by NathanKell** [comment]
@VenVen  done
@StupidChris  turns out I did have to unconflict the Utility file because your later RC patch involved FORs. Anyway, done. Also, FYI, you can have only one pass specifier (well, you can have more than one, but the patch will run on the first pass that occurs). I mention because I saw something that was :FOR[foo]:FOR[bar]....

**Pull request merged**
