### PR TITLE
Updated volumes and masses to match stock values in the 10 new tanks

### PR DESCRIPTION
**Pull request by linuxgurugamer**
These calculations were a result of rebalancing all of the KW Rocketry tanks, as well as the Munar Industries tanks and Mk2.5 spaceplane parts.

Let me know if you need to see the spreadsheet

### CODE REVIEW

**Comment by TheToric** [comment]
LF tanks should have a mass ratio of .005 (ton per unit of fuel) according to the jet fuselage. and thats before the disscussion on whether they should have a better mass ratio due to the light structure and low impact tolerance.
also, whats up with the mk5 soft tank having 4.7 LF?
LF/Ox tanks have M=(LF+OX)*.000625 for thier masses, but you are fairly close. still might want to take a look at it. 
What are the volume calcs based off of?  stock tanks?

**Comment by linuxgurugamer** [comment]
I'll take a look at the values for the LF tanks again. 
Looks like I made a mistake on the mk5 tank when copying, I'll have to fix that.

The volumes were taken from the actual dimensions of the tanks which KSP sees, I dumped that data and then added it to the spreadsheet

**Comment by TheToric** [comment]
well coulor me supprised! the mass ratio of the LF tanks varies quite a bit... however, i cannot find a single stock LF only tank that has a mass ratio of .0009. with the exeption of the miniFuselage, (ratio of 0.0005) all the stock tanks have ratios of .000714. (or withing floating point error of it...) of course, we may want to drop that a bit due to 'low impact tolerance' or somesutch.
I was more wondering if the lf/volume was in line with the stock tanks.

**Comment by linuxgurugamer** [comment]
I forget the specifics, but this is what we settled on.  And it really isn't that much different than the .0007

**Comment by TheToric** [comment]
no, its not mutch diffrent than the .0007. but .0007 is quite a bit diffrent than .0009.
not trying to be a stickler, but .0009 seems way to high for a tank...

**Comment by Kerbas-ad-astra** [comment]
I'd always thought the CryoX and especially the soft fuel tanks were supposed to be substantially lighter than stock, because their structural fraction been reduced (represented by the lower crash tolerance).

**Comment by linuxgurugamer** [comment]
Ok, I suppose I can adjust that.  But the volumes were also off, which are now correct.
So, give me a percentage of stock you want me to adjust it by and I'll do that.
ie:  Since stock uses a standard fuel mass ratio of 9:1 (ie:  8 part fuel for 1 part tank), either give me a number or a percentage to reduce it by.

**Comment by linuxgurugamer** [comment]
I have a thought:  I can look at the crash tolerances and use the difference between them as a ratio to adjust the mass accordingly.

**Comment by NathanKell** [comment]
If you want ~stockalike~, don't compute the actual volumes of parts, compare them to actual stock tanks. Remember that all propellant tanks are pressure vessels so the visual "tank" you see, except in rare cases, is just the structure surrounding the actual propellant tank(s). A 3m diameter x 5m height cylinder does *not*, and *cannot*, have a full 35 cubic meters of volume available for storage.

**Comment by TheToric** [comment]
ah, I thought that you were talking about the ratio of fuel units to tank mass (the one thats easy to see from the .cfg files.) maybye ~.0006 for the cryox tanks (a tiny bit more efficient than stock, paint savings?) and .0005 for the soft tanks? (no internal tank baffles, no outside structure, basically a balloon full of fuel)
again, in tank dry mass per unit of fuel.
so, the cryoX tanks would have 8.5 and the soft tanks would have10 tons of fuel to one ton of tank?

@NathanKell, I am pretty sure we are comparing this to stock tanks, rather than caclulating internal volume and the volume density of the fuel... (whitch we are not given by the game at all...)

**Comment by linuxgurugamer** [comment]
@NathanKell I'm not saying it's totally perfect, but the current values are way too high.  And when I apply the same calculations to the stock tanks, it turns out that they probably hold too much as well :-)
Anyway, I don't want to get into a long discussion about stock vs what should be, etc.  I'm just trying to have some reasonable values which are comparable to stock.
If everyone agrees, then I can use @TheToric 's suggestion of values.  Or, I can calculate the percentage difference in crash tolorances.

**Comment by NathanKell** [comment]
No worries, just wanted to toss that out since you mentioned calculating volumes so I thought you might be doing cylinder volumes, is all :)

**Comment by linuxgurugamer** [comment]
I just checked, the stock tanks are using a crash tolerance = 6, while the Ven's uses 4.
So I can reduce the mass by 1/3 if using this as a ratio.
Actually, I think I will use the following if it's acceptable:
This is from an Excel spreadsheet:

1-(1/SQRT(POWER(6,3) - POWER(6,3) * (4/6)))

The idea here is that the volume is 3 dimensional. So, taking the cube of the tolerance of the stock, applying this formula and multiplying the current mass by the result should be an acceptable number.  In summary, the final number is:

0.88214887 * current mass

**Comment by TheToric** [comment]
sounds good to me. although you may want to round simply so you dont get 6 digits after the decimal in the VAB.

**Comment by Kerbas-ad-astra** [comment]
Something close to the old ratio would be fine.  The old numbers for the little soft tank were 440 fuel x 0.005 t/L = 2.2 t.  The tank's old mass of 0.15 t was 1/14.667 (= 3/44) of that, which is 6/11 times the stockalike tank mass of 2.2/8 = 0.275 t.

Your recalculated volumes don't have nice common factors the way the old ones did, so there's no "obvious" choice for a new mass fraction the way that 3/44 was, but something between 1/12 and 1/16 of fuel mass (a mass discount of 30-50% vs. stock tanks) would be appropriate.

**Comment by linuxgurugamer** [comment]
@TheToric I will be rounding, that number was a copy/paste
@Kerbas-ad-astra I disagree, because reducing mass is more significant in affecting the strength of the tank.  
However, I'm willing to compromise, and use a power of 2.5 instead of 3, which would end up with a value of: 

0.815553013

Yes, i will round :-)

**Comment by Kerbas-ad-astra** [comment]
8 / 0.8 = 10, that would be a nice figure.

**Comment by linuxgurugamer** [comment]
Well, I'm going to multiply the 0.814443013 by the mass, so it will be reducing the mass by about 18.5%

**Comment by Kerbas-ad-astra** [comment]
I meant that reducing mass by 20% (multiplying by 0.8) gets back to a round number for tank masses, with 0.1 tons of tank per ton of fuel (vs. 0.125 for stock tanks).   It corresponds to a coefficient of about 2.4 with your formula, which I would argue is appropriate since fuel tanks are mostly "2D-ish" things (being cylinders or spheres containing a volume).

More broadly, I'm not sure it's consistent to use the square root in your formula -- should it be the cube root, or more generally "POW(...,-1/P)", where P is the scaling power you're using? In that case, the mass ratio is 0.7596 for cube scaling, 0.7414 for 2.5th-power-scaling, and 0.7113 for quadratic scaling.  So maybe a mass reduction of 25% (multiply by 0.75) would be appropriate.

**Comment by linuxgurugamer** [comment]
Oh, duh! grrrr.  I updated the power, missed the square root. will fix asap

**Comment by linuxgurugamer** [comment]
Ok, formula updated:  =1-1/(6^3 - 6^3 * (4/6))^(1/3)
which equals 0.7596
and I think that is mostly in agreement with what you said.
It lowers the mass a bit, I'll be pushing an update in a minute with these changes

**Comment by linuxgurugamer** [comment]
Ven,

Thanks for letting us discuss this, it was fun and very useful.  And thanks for merging it

**Comment by TheToric** [comment]
i hate to rain on your parade, but these are still heavier than LF airplane tanks per unit of fuel...

**Pull request merged**
