### PR TITLE
Ongoing revisions

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**

### CODE REVIEW

**Comment by khr15714n** [comment]
Started KSP:
_KSP Add-on Version Checker
VenStockRevamp 1.9.5 (current) 1.9.7 (avail)_

Installed through CKAN, listed as 1.9.6
1st came here, wondered were 1.9.7 is and download 1.9.6
Compared installed files with downloaded ... 100% identical
downloaded (github) VenStockRevamp.version reads 
  "VERSION": {
    "MAJOR": 1,
    "MINOR": 9,
	"PATCH": 5
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 1,
    "PATCH": 3
  }
while
http://forum.kerbalspaceprogram.com/index.php?/topic/83696-122-stock-part-revamp-update-196-released-source-files/
reads 1.2.2 and version 1.9.6

**Comment by blowfishpro** [comment]
@khr15714n It only shows up on CKAN when there's an official release, however AVC will check whatever is in the repository.

**Comment by khr15714n** [comment]
@blowfishpro As described in my original post, CKAN served me https://github.com/VenVen/Stock-Revamp/releases/tag/v1.9.6, released on Feb 4th.
VenStockRevamp.version still claims to be version 1.9.5 while it's actually 1.9.6

What I failed to mention exactly in my original post: On May 5th @Kerbas-ad-astra changed another 3 files

On start KSP showed a conflict: 1.9.5 (current) and 1.9.7 (available).
Updating the 3 files manually and changing the version file solved the problem KSP showing the conflict (for me).
Nonetheless the v1.9.6.zip has an outdated version file claiming to be 1.9.5 instead of 1.9.6.

While I came here was based on a new conflict (1.9.5 vs 1.9.7) the old one (1.9.5 vs 1.9.6) is still viable.

**Comment by blowfishpro** [comment]
Okay, so the problem is that the .version file in the 1.9.6 download actually says 1.9.5

**Comment by khr15714n** [comment]
That's what @tstivers1990 reported on April 17th in #105 
@Kerbas-ad-astra "Should be fixed by #100." on May 7th
A few hours later @VenVen merged the files but has not officially released 1.9.7 yet.
I downloaded and installed the mod on May 9th and on start KSP showed the (new) conflict between 1.9.5 (local version file) and 1.9.7 (github).

**Pull request merged**
