### PR TITLE
Removed COM Offsets

### PR DESCRIPTION
**Pull request by TheToric**
some people at the forums were wondering about the COM offsets. they were causing some unbalanced tourqes. removed the problem ones.

Or did you perhaps mean for them to be on the z axis? (the offsets were on the y axis.)

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
Those offsets are intentional, to allow the pod to be passively stable in a lifting configuration.  (They do cause a bit of trouble for docking.)

**Comment by TheToric** [comment]
ok. never seen another mod do it. Is it worth it to have for re-entry, in your opinion?
(Im kinda a bad judge of it, I do too much docking/long burns and not enough passive re-entry.)

**Comment by VenVen** [comment]
The main reason I included the offsets was to compensate for the lack of a yaw thruster in the LES. So I'd suggest either removing the offset on the MK1 pod and keep the offset on the MK1-2, or make and balance an offset to the LES itself.

**Comment by TheToric** [comment]
@VenVen, let me see what i can do. for now, chaning it to only remove offset from the mk1.

**Pull request merged**
