### PR TITLE
Ajusted tank masses to be closer to intended values, tanks no longer start empty.

### PR DESCRIPTION
**Pull request by TheToric**
some of the tank dry masses were >.01T off. no real gameplay consequences, but it was having some more noticable impacts in the soft tanks LH2 patch. all tank masses are now within .05T of .0047475T per unit of LF held, as figured out by applying linuxgurugamers calculations to a hypothetical 1LF tank.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Ummm, have you ever heard of rounding?  someone requested that I round, so I did.  which would come up with a .01T difference.
Not a big deal, but saying that the calculations are off due to rounding, when I was asked to round, kind of doesn't make sense.
and as you say, it doesn't really affect gameplay

**Comment by TheToric** [comment]
fair play. just getting them closer to actual values, without adding an extra decimal. helps out the soft tanks patch.

**Comment by VenVen** [comment]
Is there any way to make the tanks explode from G-forces? The idea behind making the tanks start empty was that they're supposed to be too fragile to launch full.

**Comment by TheToric** [comment]
@VenVen, not directly that i can see from the wiki, (not that the wiki is that well updated, but still.)
hwoever, what if you messed around with breakingForce and breakingTourqe? not exactly what you wanted (makes the part seperate instead of explode) but it may be the best you can get without plugin work.

**Comment by blowfishpro** [comment]
@VenVen parts have `maxPressure` and `gTolerance` fields which can be configured (by default they can withstand `50g` and `4 MPa`, note that pressure is combined static + dynamic)

**Comment by TheToric** [comment]
@blowfishpro, thanks. wiki must be out of date... again.
however, @VenVen, remember that a part will experience the same g-forces whether the tank is empty or full. if anything, launching a tank full will help limit your max acceleration.

**Comment by VenVen** [comment]
@blowfishpro Ah, ok, thanks for the info on those settings. I'll do a bit of fiddling around in various areas to see what works.
@TheToric , Ok, then it makes more sense to start them off full. Silly me thinking that making them spawn dry would help. XD

**Pull request merged**
