### PR TITLE
Adding compatability patches, consolidating compatability patches.

### PR DESCRIPTION
**Pull request by TheToric**
also adds .gitignore, just a file telling git to ignore the .directory file, used by linux to keep track of some things in the GUI filemanager. you can add other lines to tell git to ignore certain files. delete it if you want.

### CODE REVIEW

**Comment by PhineasFreak** [comment]
@TheToric Is it OK that the USI patches are missing a NEEDS check?

**Comment by TheToric** [comment]
@PhineasFreak, thanks, didnt notice that. these changes were given to me by another forum user. should have checked more carefully. ill get it fixed by tonight.

**Comment by TheToric** [comment]
the LH2 patch needs to wait untill  #110 is settled...

**Comment by VenVen** [comment]
@TheToric, my main issue is with the small tent, according to the spreadsheet, it should weigh 100kg(220lbs) for a single Kerbal. Considering that Kerbals should be able to pick up the object and set it up themselves with KIS(?), 220lbs is too heavy to be reasonable. 70-50kg is a more sensible range.

**Comment by TheToric** [comment]
@VenVen, 1 kerbal can pick up up to 1T with KIS, and even a real life EVA suit weighs 115 KG. it cant just be fabric, it has to be pressure rated, as well as containing life support systems.
the most similar part from MKS is the ranger minihab, coming in at 1.45T. how about we go with .8 and set the hab months to 5?

**Pull request merged**
